slack failed&success notification + build

diff --git a/.github/workflows/test_converage.yml b/.github/workflows/test_converage.yml
--- a/.github/workflows/test_converage.yml
+++ b/.github/workflows/test_converage.yml
@@ -5,27 +5,33 @@ on: [push]
 
 jobs:
   # build
+  # failing-job:
+  #   runs-on: ubuntu-latest
+
+  #   strategy:
+  #     matrix:
+  #       node-version: [20.x,21.x,22.x]
+
+  #   steps:
+  #   # - name: Checkout repository
+  #   #   uses: actions/checkout@v2
+
+  #   - name: Set up Node.js ${{ matrix.node-version }}
+  #     uses: actions/setup-node@v1
+  #     with:
+  #       node-version: ${{ matrix.node-version }}
+
+  #   - name: Install dependencies
+  #     run: npm install
+
+  #   - name: Run the tests
+  #     run: npm test -- --coverage
   failing-job:
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [20.x,21.x,22.x]
-
     steps:
-    # - name: Checkout repository
-    #   uses: actions/checkout@v2
-
-    - name: Set up Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v1
-      with:
-        node-version: ${{ matrix.node-version }}
-
-    - name: Install dependencies
-      run: npm install
-
-    - name: Run the tests
-      run: npm test -- --coverage
+    - name: failing step
+      #run: exit 1
+      run: echo "Error"
 
   # notification on success    
   on-success:
@@ -34,20 +40,19 @@ jobs:
     needs:
       - failing-job
     steps:
-      - uses: actions/checkout@v2
       - name: Slack Notification
         uses: slackapi/slack-github-action@v1.26.0
         with:
           channel-id: 'C073DKR20GL'
           payload: |
             {
-              "text": "[OK] Slack Notification succeeded: ${{ github.run_id }}\n${{ github.run_url }}",
+              "text": "[OK] test-Code Coverage succeeded: ${{ github.run_id }}\n${{ github.run_url }}",
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "[OK] Slack Notification succeeded: ${{ github.run_id }}\n${{ github.run_url }}"
+                    "text": "[OK] test-Code Coverage succeeded: ${{ github.run_id }}\n${{ github.run_url }}"
                   }
                 }
               ]
@@ -62,20 +67,19 @@ jobs:
     needs:
       - failing-job
     steps:
-    - uses: actions/checkout@v2
     - name: Slack Notification
       uses: slackapi/slack-github-action@v1.26.0
       with:
         channel-id: 'C073DKR20GL'
         payload: |
           {
-            "text": "[x] Slack Notification failed: ${{ github.run_id }}\n${{ github.run_url }}",
+            "text": "[x] test-Code Coverage failed: ${{ github.run_id }}\n${{ github.run_url }}",
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
-                  "text": "[x] Slack Notification failed: ${{ github.run_id }}\n${{ github.run_url }}"
+                  "text": "[x] test-Code Coverage failed: ${{ github.run_id }}\n${{ github.run_url }}"
                 }
               }
             ]
